#!/bin/bash
echo "Reading config file"
. ./crawl.config
mkdir -p $OUTPUTDIR
echo "Starting crawl"
while read asin 
do
	echo "Downloading ASIN: $asin"
	curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" -o "$OUTPUTDIR/$asin.html" "https://www.amazon.com/product-reviews/$asin/ref=cm_cr_dp_d_show_all_top?ie=UTF8&reviewerType=all_reviews"
	waitperiod=$(shuf -i $WAITSTART-$WAITEND -n 1)
	echo "Sleeping for $waitperiod seconds"
	sleep $waitperiod
done < $ASINLIST
